# Site settings
title:       nxtexploit
email:       aziz@nxtexploit.com
author:      Aziz Al Aman
description: "Cyber Security, Bug Bounties, CTF"
baseurl:     "blog/"
url:         "https://nxtexploit.com"
date_format: "%b %-d, %Y"
header_pages: 
 - home.html
 - blog.md
 - about.md
 - contact.html

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: true
enable_mathjax: true
extended_fonts: true
enable_anchorjs: true
# Preview image for social media aka og:image and twitter:image
post_preview_image: true

# Social icons
linkedin_username: nxtexploit
twitter_username: nxtexploit
github_username: nxtexploit


# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     7
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor
  
# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments: true
facebook_appid:
facebook_comments_number: 10
